// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADM-MSES0Lmvjc-u1ZCH-ySoll5scKmUQ',
    appId: '1:184860512706:web:aa813378d3456153a9465b',
    messagingSenderId: '184860512706',
    projectId: 'fitnessapp-464a8',
    authDomain: 'fitnessapp-464a8.firebaseapp.com',
    storageBucket: 'fitnessapp-464a8.appspot.com',
    measurementId: 'G-81MK2428KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnlAdcPEKp7VAIFwz5B5-g8MPhoQUJEQ',
    appId: '1:184860512706:android:909f6a649934794ba9465b',
    messagingSenderId: '184860512706',
    projectId: 'fitnessapp-464a8',
    storageBucket: 'fitnessapp-464a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbO0Pe3qx82oiDthPCEzhPYV8EY0Mkqw',
    appId: '1:184860512706:ios:7fcaefd8796d47e4a9465b',
    messagingSenderId: '184860512706',
    projectId: 'fitnessapp-464a8',
    storageBucket: 'fitnessapp-464a8.appspot.com',
    iosBundleId: 'com.example.fitnessapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbO0Pe3qx82oiDthPCEzhPYV8EY0Mkqw',
    appId: '1:184860512706:ios:7fcaefd8796d47e4a9465b',
    messagingSenderId: '184860512706',
    projectId: 'fitnessapp-464a8',
    storageBucket: 'fitnessapp-464a8.appspot.com',
    iosBundleId: 'com.example.fitnessapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADM-MSES0Lmvjc-u1ZCH-ySoll5scKmUQ',
    appId: '1:184860512706:web:7ffb227e43378a92a9465b',
    messagingSenderId: '184860512706',
    projectId: 'fitnessapp-464a8',
    authDomain: 'fitnessapp-464a8.firebaseapp.com',
    storageBucket: 'fitnessapp-464a8.appspot.com',
    measurementId: 'G-BTPMVTDB1X',
  );
}
